export const FIND_A_STORE = 'findStore'
export const BUY_ONLINE = 'buyOnline'
export const BOOK_NOW = 'bookNow'
export const ALL = 'All'
export const LOCAL = 'Local Ad'
export const SPECIALTY_AD = 'Specialty Ad'
export const CONTENT = 'content'
